server:
  port: 8085
mysql:
  # Specity the IP address, port number and the name of your database
  write_url: jdbc:mysql://[database-IP]:[port]/[db_name]?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
  # Enter the username
  write_username: [db_username]
  # Enter the password
  write_password: [db_password]
  # Specity the IP address, port number and the name of your database
  read_url: jdbc:mysql://[database-IP]:[port]/[db_name]?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
  # Enter the username
  read_username: [db_username]
  # Enter the password
  read_password: [db_password]

chain:
  # Node's JSON-RPC interface of the default chain
  nodeRpcAddress: "http://[node-IP]:[node-rpc-port]"
  # Default chain's netWork ID, do not change this parameter
  chainId: 9090
  # Query the transaction pool's waiting time: millisecond, recommended 1.5 seconds
  txPoolSleep: 1500
  # Path of the Keystore file
  walletFilePath: "[your-directory]/wallet"
  # After the system started, the event parsing can be started from this block height. This number can be determined based on the latest block height before the system started.
  blockHeight: [10000]

task:
  # Whether to start a timed task to submit a transaction/time parse
  enabled: true
  # Parse event
  eventAnalytics: "0/2 * * * * ?"
  # Submit Gas Credit top-up transaction
  gasRechargeSubmit: "0/10 * * * * ?"
  # Query Gas Credit top-up result
  gasRechargeResult: "0/10 * * * * ?"
  # Submit node registration application
  nodeUpChain: "0/10 * * * * ?"
  # Query transaction status
  checkTxStates: "0/10 * * * * ?"
  # Query gasPrice
  chainGasPrice: "0/60 * * * * ?"

metaTx:
  # Only used by the default chain, do not change this configuration
  chainId: 1
  # Effective time period, in hour
  deadline: 12
  # Do not change this configuration
  domainSeparator: "0x9d5e39915081369daa50abc8dc23f93c9c174abc4fc01efd13e3660e5d080276"
  # Do not change this configuration
  metaTransferTypeHash: "0xbf13ac0a2964a57037372fadd1f7b4fa6785ffdc315c85dfe8d1f9b1b01a7a51"
